import type { Alert } from "@/lib/types";
import { currentFactory } from "./factories";

export const alerts: Alert[] = [
  {
    id: "alert-0001",
    factoryId: currentFactory.id,
    lineId: "line-smt-03",
    lineName: "SMT Line 03",
    machineId: "machine-l3-aoi",
    machineName: "AOI-03",
    severity: "CRITICAL",
    status: "OPEN",
    title: "AOI-03 inspection halted",
    message: "Camera calibration fault detected — false call rate spiked to 12.8%. Inspection paused.",
    createdAt: "2026-06-12T09:18:00+05:30",
  },
  {
    id: "alert-0002",
    factoryId: currentFactory.id,
    lineId: "line-smt-03",
    lineName: "SMT Line 03",
    machineId: null,
    machineName: null,
    severity: "CRITICAL",
    status: "OPEN",
    title: "SMT Line 03 placed on HOLD",
    message: "Line halted pending AOI-03 recalibration. 3 boards currently stuck at Placement-03.",
    createdAt: "2026-06-12T09:20:00+05:30",
  },
  {
    id: "alert-0003",
    factoryId: currentFactory.id,
    lineId: "line-smt-02",
    lineName: "SMT Line 02",
    machineId: "machine-l2-spi",
    machineName: "SPI-02",
    severity: "WARNING",
    status: "OPEN",
    title: "Solder paste height drift",
    message: "SPI-02 average paste height trending high (134 µm vs 120 µm target) over last 30 boards.",
    createdAt: "2026-06-12T09:05:00+05:30",
  },
  {
    id: "alert-0004",
    factoryId: currentFactory.id,
    lineId: "line-smt-03",
    lineName: "SMT Line 03",
    machineId: "machine-l3-reflow",
    machineName: "Reflow-03",
    severity: "WARNING",
    status: "ACKNOWLEDGED",
    title: "Reflow-03 offline for scheduled PM",
    message: "Preventive maintenance window in progress. Expected back online by 11:30.",
    acknowledgedById: "user-supervisor-01",
    acknowledgedAt: "2026-06-12T08:30:00+05:30",
    createdAt: "2026-06-12T08:15:00+05:30",
  },
  {
    id: "alert-0005",
    factoryId: currentFactory.id,
    lineId: "line-smt-03",
    lineName: "SMT Line 03",
    machineId: null,
    machineName: null,
    severity: "WARNING",
    status: "OPEN",
    title: "WIP aging threshold exceeded",
    message: "3 boards have been at Placement-03 for over 60 minutes — bottleneck risk.",
    createdAt: "2026-06-12T09:25:00+05:30",
  },
  {
    id: "alert-0006",
    factoryId: currentFactory.id,
    lineId: "line-smt-01",
    lineName: "SMT Line 01",
    machineId: null,
    machineName: null,
    severity: "CRITICAL",
    status: "ACKNOWLEDGED",
    title: "X-Out rate spike — Batch 2026-06-11-A",
    message: "2 boards flagged X-Out for solder bridging on U12/U14. QE review in progress.",
    acknowledgedById: "user-quality-01",
    acknowledgedAt: "2026-06-11T17:45:00+05:30",
    createdAt: "2026-06-11T17:20:00+05:30",
  },
  {
    id: "alert-0007",
    factoryId: currentFactory.id,
    lineId: "line-smt-02",
    lineName: "SMT Line 02",
    machineId: null,
    machineName: null,
    severity: "INFO",
    status: "OPEN",
    title: "Work order WO-2026-1004 queued",
    message: "Telematics Control Unit Rev A (1,200 units) released to SMT Line 02, starts at 18:00.",
    createdAt: "2026-06-12T07:50:00+05:30",
  },
  {
    id: "alert-0008",
    factoryId: currentFactory.id,
    lineId: null,
    lineName: null,
    machineId: null,
    machineName: null,
    severity: "WARNING",
    status: "OPEN",
    title: "Rack A1 nearing capacity",
    message: "Rack A1 bins are at 92% occupancy. Plan overflow to Rack B2.",
    createdAt: "2026-06-12T09:10:00+05:30",
  },
  {
    id: "alert-0009",
    factoryId: currentFactory.id,
    lineId: "line-smt-01",
    lineName: "SMT Line 01",
    machineId: null,
    machineName: null,
    severity: "INFO",
    status: "RESOLVED",
    title: "Work order WO-2026-0998 completed",
    message: "1,800 / 1,800 units completed on SMT Line 01 — 99.4% yield.",
    resolvedById: "user-supervisor-01",
    resolvedAt: "2026-06-11T17:55:00+05:30",
    createdAt: "2026-06-11T17:50:00+05:30",
  },
  {
    id: "alert-0010",
    factoryId: currentFactory.id,
    lineId: null,
    lineName: null,
    machineId: null,
    machineName: null,
    severity: "INFO",
    status: "RESOLVED",
    title: "Shift handover completed",
    message: "Night shift handed over to day shift. All lines reviewed and confirmed operational.",
    resolvedById: "user-supervisor-01",
    resolvedAt: "2026-06-12T06:05:00+05:30",
    createdAt: "2026-06-12T06:00:00+05:30",
  },
];
