import type { Machine } from "@/lib/types";

const NOW = "2026-06-12T09:42:00+05:30";
const STALE = "2026-06-12T08:15:00+05:30";

export const machines: Machine[] = [
  // ---- SMT Line 01 (RUNNING, healthy) ----
  {
    id: "machine-l1-printer",
    lineId: "line-smt-01",
    name: "Printer-01",
    type: "PRINTER",
    sequence: 1,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "8.2s", pastePressure: "62 N" },
  },
  {
    id: "machine-l1-spi",
    lineId: "line-smt-01",
    name: "SPI-01",
    type: "SPI",
    sequence: 2,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "7.9s", avgHeight: "121 µm" },
  },
  {
    id: "machine-l1-placement",
    lineId: "line-smt-01",
    name: "Placement-01",
    type: "PLACEMENT",
    sequence: 3,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "12.4s", cph: "1,840" },
  },
  {
    id: "machine-l1-reflow",
    lineId: "line-smt-01",
    name: "Reflow-01",
    type: "REFLOW",
    sequence: 4,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { peakTemp: "245°C", zoneCount: "8" },
  },
  {
    id: "machine-l1-aoi",
    lineId: "line-smt-01",
    name: "AOI-01",
    type: "AOI",
    sequence: 5,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "9.1s", falseCallRate: "0.4%" },
  },

  // ---- SMT Line 02 (RUNNING, degraded — SPI drifting) ----
  {
    id: "machine-l2-printer",
    lineId: "line-smt-02",
    name: "Printer-02",
    type: "PRINTER",
    sequence: 1,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "8.6s", pastePressure: "58 N" },
  },
  {
    id: "machine-l2-spi",
    lineId: "line-smt-02",
    name: "SPI-02",
    type: "SPI",
    sequence: 2,
    status: "WARNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "8.0s", avgHeight: "134 µm (drift)" },
  },
  {
    id: "machine-l2-placement",
    lineId: "line-smt-02",
    name: "Placement-02",
    type: "PLACEMENT",
    sequence: 3,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "13.1s", cph: "1,720" },
  },
  {
    id: "machine-l2-reflow",
    lineId: "line-smt-02",
    name: "Reflow-02",
    type: "REFLOW",
    sequence: 4,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { peakTemp: "243°C", zoneCount: "8" },
  },
  {
    id: "machine-l2-aoi",
    lineId: "line-smt-02",
    name: "AOI-02",
    type: "AOI",
    sequence: 5,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "9.4s", falseCallRate: "0.9%" },
  },

  // ---- SMT Line 03 (HOLD — AOI critical fault, Reflow offline) ----
  {
    id: "machine-l3-printer",
    lineId: "line-smt-03",
    name: "Printer-03",
    type: "PRINTER",
    sequence: 1,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "8.4s", pastePressure: "60 N" },
  },
  {
    id: "machine-l3-spi",
    lineId: "line-smt-03",
    name: "SPI-03",
    type: "SPI",
    sequence: 2,
    status: "RUNNING",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "8.1s", avgHeight: "118 µm" },
  },
  {
    id: "machine-l3-placement",
    lineId: "line-smt-03",
    name: "Placement-03",
    type: "PLACEMENT",
    sequence: 3,
    status: "HOLD",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "—", cph: "0" },
  },
  {
    id: "machine-l3-reflow",
    lineId: "line-smt-03",
    name: "Reflow-03",
    type: "REFLOW",
    sequence: 4,
    status: "OFFLINE",
    lastHeartbeat: STALE,
    metrics: { peakTemp: "—", zoneCount: "8" },
  },
  {
    id: "machine-l3-aoi",
    lineId: "line-smt-03",
    name: "AOI-03",
    type: "AOI",
    sequence: 5,
    status: "CRITICAL",
    lastHeartbeat: NOW,
    metrics: { cycleTime: "—", falseCallRate: "12.8%" },
  },
];
